/**
 * UnoCSS metadata collected for one utility token
 */
export interface UtilityAnalysis {
  /**
   * Numeric ranks for responsive breakpoint variants
   */
  breakpoints?: Record<string, number>

  /**
   * UnoCSS layer that generated the utility
   */
  layer?: string

  /**
   * Numeric order of the UnoCSS layer
   */
  layerOrder?: number

  /**
   * Sort value supplied by UnoCSS rule metadata
   */
  metaSort?: number

  /**
   * CSS properties generated by the utility
   */
  properties: string[]

  /**
   * Whether UnoCSS recognizes the utility
   */
  recognized: boolean

  /**
   * Whether the utility resolves through an UnoCSS shortcut
   */
  shortcut: boolean

  /**
   * Numeric rule order assigned by UnoCSS
   */
  unoOrder?: number
}
