/**
 * UnoCSS metadata collected for one utility token
 */
export interface UtilityAnalysis {
  /**
   * Utility name after UnoCSS removes variants, importance, negativity, and a
   * configured preset prefix
   */
  base?: string

  /**
   * Numeric ranks for responsive breakpoint variants
   */
  breakpoints?: Record<string, number>

  /**
   * UnoCSS layer that generated the utility
   */
  layer?: string

  /**
   * Numeric order of the UnoCSS layer
   */
  layerOrder?: number

  /**
   * Sort value supplied by UnoCSS rule metadata
   */
  metaSort?: number

  /**
   * Token rank used by UnoCSS's official class sorter
   */
  officialOrder?: number

  /**
   * Preset prefix matched by the utility
   */
  prefix?: string

  /**
   * CSS properties generated by the utility
   */
  properties: string[]

  /**
   * Whether UnoCSS recognizes the utility
   */
  recognized: boolean

  /**
   * Variant separators from the resolved UnoCSS configuration
   */
  separators?: string[]

  /**
   * Whether the utility resolves through an UnoCSS shortcut
   */
  shortcut: boolean

  /**
   * Numeric rule order assigned by UnoCSS
   */
  unoOrder?: number

  /**
   * Variant names parsed by the resolved UnoCSS configuration
   */
  variants?: string[]
}
