/* eslint-disable max-lines */

/**
 * Direction used when sorting utility classes
 */
export type SortOrder = 'asc' | 'desc'

/**
 * Strategy used to compare utility classes within a group
 */
export type SortType =
  | 'semantic'
  | 'uno'
  | 'natural'
  | 'alphabetical'
  | 'code-point'
  | 'custom'
  | 'unsorted'

/**
 * Sorting strategies available after the primary comparison is equal
 */
export type FallbackSortType = Exclude<SortType, 'semantic' | 'uno'>

/**
 * Behavior applied to special characters before string comparison
 */
export type SpecialCharacters = 'keep' | 'trim' | 'remove'

/**
 * Regular expression represented by a pattern string or an explicit descriptor
 */
export type RegexOption =
  | string
  | {
      /**
       * Flags passed to the regular expression constructor
       */
      flags?: string

      /**
       * Source pattern passed to the regular expression constructor
       */
      pattern: string
    }

/**
 * Secondary comparison used when the primary comparison is equal
 */
export interface FallbackSort {
  /**
   * Direction applied to the fallback comparison
   */
  order?: SortOrder

  /**
   * Strategy used by the fallback comparison
   */
  type: FallbackSortType
}

/**
 * Per-group overrides for utility sorting behavior
 */
export interface GroupOverride {
  /**
   * Secondary comparison used within the group
   */
  fallbackSort?: FallbackSort

  /**
   * Group name or names that receive these overrides
   */
  group: string | string[]

  /**
   * Direction used within the group
   */
  order?: SortOrder

  /**
   * Comparison strategy used within the group
   */
  type?: SortType
}

/**
 * Utility group entry represented by names or a behavior override
 */
export type GroupOption = string | string[] | GroupOverride

/**
 * Conditions used to assign a utility to a custom group
 */
export interface CustomGroupMatch {
  /**
   * Match utilities that use or do not use arbitrary property syntax
   */
  arbitrary?: boolean

  /**
   * Match the complete utility class name
   */
  classNamePattern?: RegexOption

  /**
   * Match a CSS property generated by the utility
   */
  cssPropertyPattern?: RegexOption

  /**
   * Match one or more UnoCSS layers
   */
  layer?: string | string[]

  /**
   * Match utilities recognized or not recognized by UnoCSS
   */
  recognized?: boolean

  /**
   * Match utilities that are or are not UnoCSS shortcuts
   */
  shortcut?: boolean

  /**
   * Match a variant attached to the utility
   */
  variantNamePattern?: RegexOption
}

/**
 * Named custom utility group with matching and sorting behavior
 */
export type CustomGroup = {
  /**
   * Secondary comparison used within the custom group
   */
  fallbackSort?: FallbackSort

  /**
   * Name used to position the custom group
   */
  groupName: string

  /**
   * Direction used within the custom group
   */
  order?: SortOrder

  /**
   * Comparison strategy used within the custom group
   */
  type?: SortType
} & (
  | CustomGroupMatch
  | {
      /**
       * Alternative matchers where any one can select the custom group
       */
      anyOf: CustomGroupMatch[]
    }
)

/**
 * Custom mapping from variant names to a variant group
 */
export interface CustomVariantGroup {
  /**
   * Name used to position the variant group
   */
  groupName: string

  /**
   * Pattern used to select variants for the group
   */
  variantNamePattern: RegexOption
}

/**
 * Options controlling how UnoCSS variants are ordered
 */
export interface VariantOptions {
  /**
   * Direction used to compare compound variant chains
   */
  compoundOrder?: 'outer-first' | 'inner-first'

  /**
   * User-defined variant group matchers
   */
  customGroups?: CustomVariantGroup[]

  /**
   * Ordered variant groups where nested arrays share a rank
   */
  groups?: (string | string[])[]

  /**
   * Placement of variants relative to utility groups
   */
  placement?: 'grouped' | 'attached'

  /**
   * Strategy used to order responsive variants
   */
  responsiveOrder?: 'theme' | 'source' | 'natural'
}

/**
 * User-facing options for the UnoCSS class ordering rule
 */
export interface OrderOptions {
  /**
   * Alphabet used by the custom comparison strategy
   */
  alphabet?: string

  /**
   * User-defined utility groups and their matchers
   */
  customGroups?: CustomGroup[]

  /**
   * Secondary comparison used when the primary comparison is equal
   */
  fallbackSort?: FallbackSort

  /**
   * Ordered utility groups and per-group overrides
   */
  groups?: GroupOption[]

  /**
   * Whether string comparisons ignore letter casing
   */
  ignoreCase?: boolean

  /**
   * Locale or locales used by collation-based comparisons
   */
  locales?: string | string[]

  /**
   * Default direction used within utility groups
   */
  order?: SortOrder

  /**
   * Whether each newline-delimited section is sorted independently
   */
  partitionByNewLine?: boolean

  /**
   * Placement behavior for UnoCSS shortcuts
   */
  shortcuts?: 'expanded' | 'preserve-position' | 'group'

  /**
   * Behavior applied to special characters before comparison
   */
  specialCharacters?: SpecialCharacters

  /**
   * Default comparison strategy used within utility groups
   */
  type?: SortType

  /**
   * Placement behavior for unrecognized utilities
   */
  unknown?: 'preserve-position' | 'group'

  /**
   * Additional attribute names or patterns containing UnoCSS utilities
   */
  unoAttributes?: RegexOption[]

  /**
   * Function names whose arguments contain UnoCSS utilities
   */
  unoFunctions?: string[]

  /**
   * Variable name patterns whose values contain UnoCSS utilities
   */
  unoVariables?: RegexOption[]

  /**
   * Options controlling variant classification and ordering
   */
  variants?: VariantOptions
}

/**
 * Fully resolved variant options used by the sorting engine
 */
export interface ResolvedVariantOptions {
  /**
   * Direction used to compare compound variant chains
   */
  compoundOrder: 'outer-first' | 'inner-first'

  /**
   * Resolved user-defined variant group matchers
   */
  customGroups: CustomVariantGroup[]

  /**
   * Resolved ordered variant groups
   */
  groups: (string | string[])[]

  /**
   * Placement of variants relative to utility groups
   */
  placement: 'grouped' | 'attached'

  /**
   * Strategy used to order responsive variants
   */
  responsiveOrder: 'theme' | 'source' | 'natural'
}

/**
 * Fully resolved ordering options used by the sorting engine
 */
export interface ResolvedOrderOptions {
  /**
   * Alphabet used by the custom comparison strategy
   */
  alphabet: string

  /**
   * Resolved custom utility groups
   */
  customGroups: CustomGroup[]

  /**
   * Resolved secondary comparison
   */
  fallbackSort: FallbackSort

  /**
   * Resolved ordered utility groups
   */
  groups: GroupOption[]

  /**
   * Whether string comparisons ignore letter casing
   */
  ignoreCase: boolean

  /**
   * Locales used by collation-based comparisons
   */
  locales: string | string[]

  /**
   * Default direction used within utility groups
   */
  order: SortOrder

  /**
   * Whether each newline-delimited section is sorted independently
   */
  partitionByNewLine: boolean

  /**
   * Placement behavior for UnoCSS shortcuts
   */
  shortcuts: 'expanded' | 'preserve-position' | 'group'

  /**
   * Behavior applied to special characters before comparison
   */
  specialCharacters: SpecialCharacters

  /**
   * Default comparison strategy used within utility groups
   */
  type: SortType

  /**
   * Placement behavior for unrecognized utilities
   */
  unknown: 'preserve-position' | 'group'

  /**
   * Additional attribute patterns containing UnoCSS utilities
   */
  unoAttributes: RegexOption[]

  /**
   * Function names whose arguments contain UnoCSS utilities
   */
  unoFunctions: string[]

  /**
   * Variable name patterns whose values contain UnoCSS utilities
   */
  unoVariables: RegexOption[]

  /**
   * Resolved variant ordering options
   */
  variants: ResolvedVariantOptions
}

/**
 * UnoCSS metadata collected for one utility token
 */
export interface UtilityAnalysis {
  /**
   * Numeric ranks for responsive breakpoint variants
   */
  breakpoints?: Record<string, number>

  /**
   * UnoCSS layer that generated the utility
   */
  layer?: string

  /**
   * Numeric order of the UnoCSS layer
   */
  layerOrder?: number

  /**
   * Sort value supplied by UnoCSS rule metadata
   */
  metaSort?: number

  /**
   * CSS properties generated by the utility
   */
  properties: string[]

  /**
   * Whether UnoCSS recognizes the utility
   */
  recognized: boolean

  /**
   * Whether the utility resolves through an UnoCSS shortcut
   */
  shortcut: boolean

  /**
   * Numeric rule order assigned by UnoCSS
   */
  unoOrder?: number
}
